version: '3.9'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-master-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf


  redis-slave:
    image: redis:latest
    container_name: redis-slave
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-slave-data:/data
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6379

  sentinel1:
    image: redis:latest
    container_name: redis-sentinel1
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-slave
    volumes:
      - ./conf/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf


volumes:
  redis-master-data:
  redis-slave-data:
